name: Build Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        env:
          CBAT_KEY_NAME: ${{ secrets.CBAT_KEY_NAME }}
          CBAT_KEY_SECRET: ${{ secrets.CBAT_KEY_SECRET }}
        run: |
          docker swarm init
          echo "$CBAT_KEY_NAME" | docker secret create CBAT_KEY_NAME -
          echo "$CBAT_KEY_SECRET" | docker secret create CBAT_KEY_SECRET -
          docker build --secret id=CBAT_KEY_NAME --secret id=CBAT_KEY_SECRET -t cbat:latest .

      - name: Publish Crate
        id: publish
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: |
          echo "$CARGO_REGISTRY_TOKEN" | cargo login -
          cargo publish
        continue-on-error: true

      - name: OK
        run: echo "OK"
        if: job.steps.publish.status == failure()