name: Build Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker swarm init
          printenv CBAT_KEY_NAME | docker secret create CBAT_KEY_NAME -
          printenv CBAT_KEY_SECRET | docker secret create CBAT_KEY_SECRET -
          docker build --secret id=CBAT_KEY_NAME --secret id=CBAT_KEY_SECRET -t cbat:latest .
