name: Build Dockerfile

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build Docker Image
        env:
          CBAT_KEY_NAME: ${{ secrets.CBAT_KEY_NAME }}
          CBAT_KEY_SECRET: ${{ secrets.CBAT_KEY_SECRET }}
        run: |
          docker swarm init
          docker build --secret id=CBAT_KEY_NAME --secret id=CBAT_KEY_SECRET -t cbat:latest .
